### ISSUE TITLE
Inaccurate Statement

### ISSUE THREAD

**Issue by axiliquint** [sasial-dev/Portfolio#1]
The statement attached is false, you have done no work with "maintaining the bots". You have broken them in every single way possible. Please fix.

https://github.com/sasial-dev/Portfolio/blob/1cfef6a8da1cf3f20e5f6d00760ae31fe6af2e50/pages/index.vue#L61

**Comment by axiliquint** [comment]
Additionally, your attached Koal logo does not follow the Koal Internal & Technical Branding & Design Guidelines & Rules Booklet & Pamphlet. Please fix.

**Comment by sasial-dev** [comment]
Abuse
